# Generated by Django 3.1.4 on 2021-01-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
